clone:
  git:
    image: plugins/git
    tags: true

pipeline:
  test1:
    image: mhart/alpine-node:9.1.0
    group: testing
    secrets: [ test46 ]
    commands:
      - sleep 5
      - yarn install
      - echo "node.js"
      - echo $TEST46
      - node redis.js

  test2:
    image: appleboy/golang-testing
    group: testing
    secrets: [ test46, readme ]
    commands:
      - echo "golang"
      - echo $TEST46
      - echo $README

services:
  redis:
    image: redis
